export const NBR_MONTHS_IN_YEAR = 12
export const NBR_DAYS_IN_MONTH = 30
export const NBR_HOURS_IN_DAY = 24
export const NBR_MINUTES_IN_HOUR = 60
export const NBR_MINUTES_IN_DAY = NBR_MINUTES_IN_HOUR * NBR_HOURS_IN_DAY
export const NBR_MINUTES_IN_MONTH = NBR_MINUTES_IN_HOUR * NBR_HOURS_IN_DAY * NBR_DAYS_IN_MONTH
export const NBR_MINUTES_IN_YEAR = NBR_MINUTES_IN_HOUR * NBR_HOURS_IN_DAY * NBR_DAYS_IN_MONTH * NBR_MONTHS_IN_YEAR
